### ISSUE TITLE
How to remove the Git Sync menu item

### ISSUE THREAD

**Issue by 40thpower** [hibbitts-design/grav-theme-antimatter-open-publishing#1]
Let me know where to post, if this is not an appropriate place. I'm doing my first Grav site, using the Open Publishing theme. Going great so far.  However, there are two issues that stand out. First, how to remove the Git Sync item in the main menu?  I removed the Git Sync plugin, then tried adding 

hide_git_sync_repo_link: true  

in the frontmatter of a few page, but no help. What am I doing wrong?  I do not plan to use Git sync, so I need to figure this out. 

Also, how can I remove or edit the footer text with the link to Rocket Theme?  I'm sure I can eventually find this in a twig templates.  But so far I'm finding that removing a part of the templates can break the site, so it may be best to do it in a yaml setting??   

And theme inheritance is still tricky for me. Open Publishing needs Antimatter installed, and then I have my own subtheme, 'mytheme', which depends on Open Publishing and Antimatter, I assume.  In order to override anything, should I just copy any file that need editing into 'mytheme'?  I'm sorry I don't know enough to phrase the question any better.  I'm coming from a Drupal point of view, where it's always an easy thing to locate the correct template and make a change.

Thanks so much for a wonderful theme!

**Comment by paulhibbitts** [comment]
Hi @40thpower , welcome to Grav!

The Open Publishing Space was really created to work with the Git Sync plugin, but it is possible to hide that ability. If you go to the settings for the OPS theme and look for a section called 'Git Sync Link' you should see an option called `Display of Git Sync Link` and choosing `None` [Save] should then hide the Git Sync menu.

The footer in OPS is basically the same as the source theme, Antimatter, and as you noticed you would need to edit a bit of Twig to modify it. You can find the footer related Twig at https://github.com/hibbitts-design/grav-theme-antimatter-open-publishing/blob/master/templates/partials/base.html.twig#L76-L85

In my other theme, Open Course Hub, I've made it possible to edit the Footer like any other Grav page... perhaps this might be something I can look into for OPS as well...

Theme inheritance is amazing, but as you say a bit tricky when the theme in question is already an inherited theme! I suggest you download at check out my OPS Skeleton, as this already has a mytheme inherited theme all setup, etc. Skeleton can be downloaded from https://getgrav.org/downloads/skeletons (scroll down).

Please let me know how the above works out!
ps - the `hide_git_sync_repo_link: true` option only hides the link once GitSync has been configured

**Comment by paulhibbitts** [comment]
FYI - I've added a Footer page to the newest release of the theme (v1.0.8) and it should be available in the next hour or so.

**Comment by 40thpower** [comment]
Paul, thank you so much for this fix. I was able to incorporate the footer page right into my site, by first upgrading the theme, then copying the footer page into my page folder.  (I assume that when using a skeleton, you only need to upgrade the theme.) 

I can't believe how easy it is to move pieces around, which are much like Drupal's blocks, without  involving changes to a database. I expect it will take a while for people to wake up to the implications of the flat file CMS. I expect it will catch on like a California brush fire at some point!

Hopefully OSTraining will post some lessons on Grav eventually. (I learned about Grav on an OST podcast.) Meanwhile, I've gotten a lot done just using the docs provided. 

Thanks again for your hard work and creativity. I can't wait to tell all my Drupal buddies about Grav.

**Comment by paulhibbitts** [comment]
Great @40thpower, and yes the upgrade process you describe is right if using updated skeleton vs. just the theme. Themes can also have a "_demo" folder, and in there you can also find the updated pages if you are not using the new skeleton.

You might also find some of these resources about Grav helpful - https://github.com/paulhibbitts/awesome-grav

Hope you enjoy Grav🙂 I've noticed more and more Drupal folks giving it a look.
