### ISSUE TITLE
Pages not showing in menu

### ISSUE THREAD

**Issue by franck-boucher** [hibbitts-design/grav-theme-antimatter-open-publishing#2]
Hi, thx for this very beautifull theme !

I have a problem tho, I am curently playing with Grav and your theme and I don't know what I have done but my pages are not showing by default in the menu anymore.

Do you have an idée of why this behavior happens ?

**Comment by paulhibbitts** [comment]
Hi @franck-boucher, thanks very much - all the heavy lifting is done by the original Grav theme 'AntiMatter'🙂

My hunch would be the pages `visible` flag has been set to false. You can use the Admin Panel to change the visibility by editing the page and then on the **Advanced** panel set the `Visible` option to `Enabled` or you can edit the pages frontmatter directly and set it there, as shown below:

```
---
title: Test
visible: true
---
```

Also, it matters where you create the new page in the site structure. If it is in the top level (root) a numeric prefix should automatically be added to the page folder name and it should automatically be visible (i.e. visible on the site navbar). More info at https://learn.getgrav.org/content/content-pages#folders

Let me know if the above works for you.
