### ISSUE TITLE
Extra markdown issue after Antimatter Open Publishing theme upgrade to 1.2.5

### ISSUE THREAD

**Issue by bcousaert** [hibbitts-design/grav-theme-antimatter-open-publishing#3]
With the Antimatter Open Publishing theme upgrade from 1.2.3 to 1.2.5, the extra markdown [.center] in ![](myimage.jpg){.center} does no longer center the image.

**Comment by paulhibbitts** [comment]
Thanks @tx-odyssey , could you please share your Markdown and I will test with both my OPS theme and the source theme Antimatter.

**Comment by bcousaert** [comment]
Hi Paul,

first of all many thanks for the great theme. We’re using it to assemble our (enterprise) architectural work.

Please find attached the md. Note that we often use centered images in the markdown, and the problem since 1.2.5 is general (so not only for the attached page).

Best regards,

__________________
Bart @+32 478 585734

**Comment by paulhibbitts** [comment]
Thanks @tx-odyssey , glad you are finding the theme useful! The Markdown file attachment seems to not be included in your message - could you please try to add it again?

**Comment by bcousaert** [comment]
Attached renamed md extension into txt.

grtz

__________________
Bart @+32 478 585734

**Comment by paulhibbitts** [comment]
Got it, thanks!

**Comment by paulhibbitts** [comment]
@tx-odyssey Ok, I've done a quick test of enabling Markdown Extra using v1.2.5 and creating a center CSS class in my custom.CSS file and got this:

![2018-01-25_07-14-18](https://user-images.githubusercontent.com/1812771/35395692-ea2de108-019f-11e8-8518-63e567a47480.png)

Could you please verify that your CSS class is working/present?

You could also try this alternative format (which I do not think needs Markdown Extra):
`![Sample image](sample.png?classes=center)`

**Comment by bcousaert** [comment]
Paul, indeed, I forgot to put back the custom.css after the upgrade. Very sorry. 

It’s okay now. 

Our Grav site is running your theme on Azure Cloud. Was setup in a few minutes, just awesome.

If I can contribute in any way to your work, pls let me know what the options are.

Thanks a lot.

__________________
Bart @+32 478 585734

**Comment by paulhibbitts** [comment]
Great @tx-odyssey , glad you got things going again! Nice to hear that Azure Cloud works nicely with Grav too.

BTW, are you using the Git Sync feature of the theme, and if so how are you finding it?

ps - if you wish customizations to the theme to remain with updates, you might want to consider setting up an inherited theme https://learn.getgrav.org/themes/customization#theme-inheritance. As OPS is itself an inherited theme (from Antimatter) the config is a bit different, you can see a fully working example in the OPS Skeleton https://getgrav.org/downloads/skeletons
