### ISSUE TITLE
lightbox box not showing up

### ISSUE THREAD

**Issue by rafalzdeb** [hibbitts-design/grav-theme-antimatter-open-publishing#4]
When using plugin Featherbox to enable lightbox functionality it works only in original Antimatter theme. In Antimatter Open Publishing it opens a new page instead of a box.

**Comment by paulhibbitts** [comment]
Hi @rafalzdeb , is it possible for you to share an example page with images for me to take a look at this (either here or in the Grav Slack room)?

BTW, I am close to releasing an Open Publishing Space version of the Quark theme - pre-release is at https://github.com/hibbitts-design/grav-theme-quark-open-publishing and demo at http://demo.hibbittsdesign.org/grav-open-publishing-quark/

I wonder if Lightbox works with that as-is?

**Comment by rafalzdeb** [comment]
Hello Paul,

This is a source from the page in question. Clicking on a picture with
lightbox enabled in markdown get me to the picture page. Tested on Chrome
and Firefox on mac and windows.

Cheers
------------------------------------------
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Adding multiple photos | Slow Adv</title>
<meta name="generator" content="GravCMS" />
<meta name="description" content="Grav is an easy to use, yet powerful,
open source flat-file CMS" />
<meta name="viewport" content="width=device-width, initial-scale=1.0,
minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link rel="icon" type="image/png" href="
/user/themes/antimatter/images/favicon.png
<http://srv21430.microhost.com.pl/user/themes/antimatter/images/favicon.png>"
/>
<link rel="canonical" href="
http://srv21430.microhost.com.pl/blog/adding-multiple-photos" />

<link href="/user/themes/antimatter/css/pure-0.5.0/grids-min.css
<http://srv21430.microhost.com.pl/user/themes/antimatter/css/pure-0.5.0/grids-min.css>"
type="text/css" rel="stylesheet" />
<link href="/user/themes/antimatter/css-compiled/nucleus.css
<http://srv21430.microhost.com.pl/user/themes/antimatter/css-compiled/nucleus.css>"
type="text/css" rel="stylesheet" />
<link href="/user/themes/mytheme/css-compiled/template.css
<http://srv21430.microhost.com.pl/user/themes/mytheme/css-compiled/template.css>"
type="text/css" rel="stylesheet" />
<link href="/user/themes/mytheme/css/custom.css
<http://srv21430.microhost.com.pl/user/themes/mytheme/css/custom.css>" type
="text/css" rel="stylesheet" />
<link href="/user/themes/mytheme/css/theme.css
<http://srv21430.microhost.com.pl/user/themes/mytheme/css/theme.css>" type="
text/css" rel="stylesheet" />
<link href="/user/themes/antimatter/css/font-awesome.min.css
<http://srv21430.microhost.com.pl/user/themes/antimatter/css/font-awesome.min.css>"
type="text/css" rel="stylesheet" />
<link href="/user/plugins/markdown-notices/assets/notices.css
<http://srv21430.microhost.com.pl/user/plugins/markdown-notices/assets/notices.css>"
type="text/css" rel="stylesheet" />
<link href="/user/plugins/breadcrumbs/css/breadcrumbs.css
<http://srv21430.microhost.com.pl/user/plugins/breadcrumbs/css/breadcrumbs.css>"
type="text/css" rel="stylesheet" />
<link href="/user/plugins/form/assets/form-styles.css
<http://srv21430.microhost.com.pl/user/plugins/form/assets/form-styles.css>"
type="text/css" rel="stylesheet" />
<link href="/user/plugins/simplesearch/css/simplesearch.css
<http://srv21430.microhost.com.pl/user/plugins/simplesearch/css/simplesearch.css>"
type="text/css" rel="stylesheet" />
<link href="/user/plugins/youtube/css/youtube.css
<http://srv21430.microhost.com.pl/user/plugins/youtube/css/youtube.css>"
type="text/css" rel="stylesheet" />
<link href="/user/plugins/login/css/login.css
<http://srv21430.microhost.com.pl/user/plugins/login/css/login.css>" type="
text/css" rel="stylesheet" />
<link href="/user/themes/antimatter/css/slidebars.min.css
<http://srv21430.microhost.com.pl/user/themes/antimatter/css/slidebars.min.css>"
type="text/css" rel="stylesheet" />


<script src="/system/assets/jquery/jquery-2.x.min.js
<http://srv21430.microhost.com.pl/system/assets/jquery/jquery-2.x.min.js>" >
</script>
<script src="/user/themes/antimatter/js/modernizr.custom.71422.js
<http://srv21430.microhost.com.pl/user/themes/antimatter/js/modernizr.custom.71422.js>"
></script>
<script src="/user/themes/antimatter-open-publishing/js/my.js
<http://srv21430.microhost.com.pl/user/themes/antimatter-open-publishing/js/my.js>"
></script>
<script src="/user/themes/antimatter/js/antimatter.js
<http://srv21430.microhost.com.pl/user/themes/antimatter/js/antimatter.js>"
></script>
<script src="/user/themes/antimatter/js/slidebars.min.js
<http://srv21430.microhost.com.pl/user/themes/antimatter/js/slidebars.min.js>"
></script>


</head>

<body id="top" class="">

<h1 class="hidden">Adding multiple photos</h1>

<div id="sb-site">

<header id="header">
<div id="logo">
<h3><a href="/ <http://srv21430.microhost.com.pl/>">Slow Adv</a></h3>
</div>
<div id="navbar">
<ul class="navigation">
<li class="active">
<a href="/ <http://srv21430.microhost.com.pl/>">
Blog
</a>
</li>
<li class="">
<a href="/where-am-i <http://srv21430.microhost.com.pl/where-am-i>">
Where am I?
</a>
</li>
<li class="">
<a href="/modular-page <http://srv21430.microhost.com.pl/modular-page>">
Modular Page
</a>
</li>
<li class="">
<a href="/readme <http://srv21430.microhost.com.pl/readme>">
Read Me
</a>
</li>
<li> <a class="newwindow external-link" href="/admin/plugins/git-sync
<http://srv21430.microhost.com.pl/admin/plugins/git-sync>" title="Setup Git
Sync">
<i class="fa fa-cog" aria-hidden="true"></i>
Setup Git Sync</a>
</li>
</ul>
<span class="panel-activation sb-toggle-left navbar-left menu-btn fa fa-bars
"></span>
</div>
</header>
<section id="body" class="">
<div id="breadcrumbs" itemscope itemtype="
http://data-vocabulary.org/Breadcrumb">
<a href="/ <http://srv21430.microhost.com.pl/>" itemprop="url"><span
itemprop="title">Blog</span></a>
<i class="fa fa-angle-right"></i>
<span itemprop="title">Adding multiple photos</span>
</div>
<div class="blog-content-item grid pure-g-r">
<div id="item" class="block pure-u-2-3 h-entry">
<div class="list-item h-entry">

<div class="list-blog-header">
<span class="list-blog-date">
<time class="dt-published" datetime=" 2018-03-22T20:35:00+01:00">
<span>22</span>
<em>Mar</em>
</time>
</span>
<h4 class="p-name"><a href="/blog/adding-multiple-photos
<http://srv21430.microhost.com.pl/blog/adding-multiple-photos>" class="u-url
"><i class="fa fa-globe" aria-hidden="true"></i> Adding multiple photos</a>
</h4>
<span class="tags">
<a href="/tag:Poland <http://srv21430.microhost.com.pl/tag:Poland>" class="
p-category">Poland</a>
<a href="/tag:Autumn <http://srv21430.microhost.com.pl/tag:Autumn>" class="
p-category">Autumn</a>
</span>
<img src="
/images/1/c/6/4/c/1c64cb74e4ff83de2e1de1d9005330d8055ea774-victoria.jpeg
<http://srv21430.microhost.com.pl/images/1/c/6/4/c/1c64cb74e4ff83de2e1de1d9005330d8055ea774-victoria.jpeg>"
alt=""/>
</div>

<div class="list-blog-padding">

<div class="e-content">
<p><a rel="lightbox" data-width="1024" data-height="738" href="
/images/8/6/3/e/3/863e3af2f06691a5f93b8bda9a5fa88bea229734-jesien-1.jpeg
<http://srv21430.microhost.com.pl/images/8/6/3/e/3/863e3af2f06691a5f93b8bda9a5fa88bea229734-jesien-1.jpeg>
">
<img alt="" src="/user/pages/01.blog/adding-multiple-photos/Jesien-1.jpg
<http://srv21430.microhost.com.pl/user/pages/01.blog/adding-multiple-photos/Jesien-1.jpg>"
/>
</a><img alt="" src="/user/pages/01.blog/adding-multiple-photos/Jesien-3.jpg
<http://srv21430.microhost.com.pl/user/pages/01.blog/adding-multiple-photos/Jesien-3.jpg>"
/>
<img alt="" src="/user/pages/01.blog/adding-multiple-photos/Jesien-4.jpg
<http://srv21430.microhost.com.pl/user/pages/01.blog/adding-multiple-photos/Jesien-4.jpg>"
/><img alt="" src="/user/pages/01.blog/adding-multiple-photos/Jesien-2.jpg
<http://srv21430.microhost.com.pl/user/pages/01.blog/adding-multiple-photos/Jesien-2.jpg>"
/></p>
</div>

<p class="prev-next">
<a class="button" href="/blog/sunshine-in-the-hills
<http://srv21430.microhost.com.pl/blog/sunshine-in-the-hills>">
<i class="fa fa-chevron-left"></i>
Previous Post</a>
</p>

</div>
</div>
</div>

</div>
</section>
<footer id="footer">
<div class="totop">
<span><a href="#
<http://srv21430.microhost.com.pl/blog/adding-multiple-photos#>" id="toTop"><i
class="fa fa-arrow-up"></i></a></span>
</div>
<p>Built with <a href="http://getgrav.org" target="_blank" rel="nofollow
noopener noreferrer" class="external-link no-image">Grav CMS</a><br />
<a href="http://learn.hibbittsdesign.org/openpublishingspace" target="_blank"
rel="nofollow noopener noreferrer" class="external-link no-image">Open
Publishing Space</a> package by <a href="http://hibbittsdesign.org" target="
_blank" rel="nofollow noopener noreferrer" class="external-link no-image">
hibbittsdesign.org</a> </p>
</footer>
</div>
<div class="sb-slidebar sb-left sb-width-thin">
<div id="panel">
<ul class="navigation">
<li class="active">
<a href="/ <http://srv21430.microhost.com.pl/>">
Blog
</a>
</li>
<li class="">
<a href="/where-am-i <http://srv21430.microhost.com.pl/where-am-i>">
Where am I?
</a>
</li>
<li class="">
<a href="/modular-page <http://srv21430.microhost.com.pl/modular-page>">
Modular Page
</a>
</li>
<li class="">
<a href="/readme <http://srv21430.microhost.com.pl/readme>">
Read Me
</a>
</li>
<li> <a class="newwindow external-link" href="/admin/plugins/git-sync
<http://srv21430.microhost.com.pl/admin/plugins/git-sync>" title="Setup Git
Sync">
<i class="fa fa-cog" aria-hidden="true"></i>
Setup Git Sync</a>
</li>
</ul>
</div>
</div>
<script src="/user/plugins/simplesearch/js/simplesearch.js
<http://srv21430.microhost.com.pl/user/plugins/simplesearch/js/simplesearch.js>"
></script>

<script>
$(function() {
$(document).ready(function() {
$.slidebars({
hideControlClasses: true,
scrollLock: true
});
});
});
</script>
</body>



</html>
------------------------------


2018-03-27 23:06 GMT+02:00 Paul Hibbitts <notifications@github.com>:

**Comment by paulhibbitts** [comment]
Sorry, I meant a Grav Page folder with images or entire User folder @rafalzdeb

**Comment by rafalzdeb** [comment]
2018-03-27 23:14 GMT+02:00 Paul Hibbitts <notifications@github.com>:

**Comment by paulhibbitts** [comment]
Hi @rafalzdeb , I think I've tracked down the problem. Could you please replace the /js/my.js file in your theme with this one? https://github.com/hibbitts-design/grav-theme-antimatter-open-publishing/tree/master/js

Please let me know how things work out.

**Comment by rafalzdeb** [comment]
Hi Paul,

It worked!

Cheers
Rafał

2018-03-28 0:52 GMT+02:00 Paul Hibbitts <notifications@github.com>:

**Comment by paulhibbitts** [comment]
Great to hear, an update including this fix will be released soon.
